sudo: required

language: python

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - OPAC_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - OPAC_VCS_REF=$COMMIT
  - OPAC_WEBAPP_VERSION=$(cat VERSION)

services:
- docker

before_install:
- pip install docker-compose
- docker --version

script:
- docker-compose -f docker-compose-build.yml build
- docker-compose -f docker-compose-build.yml up -d
- docker exec opac_opac_webapp_1 make test
- docker run -it --net host --pid host --cap-add audit_control -v /var/lib:/var/lib
  -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd
  -v /etc:/etc --label docker_bench_security docker/docker-bench-security

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
  docker build -t $TRAVIS_REPO_SLUG:$COMMIT .;
  docker tag $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:latest;
  docker tag $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:travis-$TRAVIS_BUILD_NUMBER;
  docker push $TRAVIS_REPO_SLUG;
  fi

notifications:
  slack: scielo:6YcYDMh1STDOQT8H7umVuD0R
