version: '2'

services:

    mailhog:
        image: mailhog/mailhog:latest
        hostname: mailhog
        ports:
            - "8025:8025"
        volumes:
            - /etc/localtime:/etc/localtime:ro

    opac_mongo:
        image: mongo:latest
        restart: always
        user: mongodb
        hostname: opac-mongo
        ports:
            - "27017:27017"
        volumes:
            - /etc/localtime:/etc/localtime:ro

    opac_webapp:
        build:
            context: .
            dockerfile: ./Dockerfile-dev
            args:
                - OPAC_BUILD_DATE=${OPAC_BUILD_DATE}            # export OPAC_BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
                - OPAC_VCS_REF=${OPAC_VCS_REF}                  # export OPAC_VCS_REF=`git rev-parse --short HEAD`
                - OPAC_WEBAPP_VERSION=${OPAC_WEBAPP_VERSION}    # export OPAC_WEBAPP_VERSION="v0.1.0-dev"
        command: gunicorn --workers 3 --bind 0.0.0.0:8000 manager:app --chdir=/app/opac --reload --timeout 1000 --log-level DEBUG
        user: nobody
        restart: always
        hostname: opac_webapp
        depends_on:
            - opac_mongo
            - mailhog
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - .:/app
        links:
            - opac_mongo:opac-mongo
            - mailhog:mailhog
        ports:
            - "8000:8000"
        environment:
            - OPAC_DEBUG_MODE=True
            - OPAC_MONGODB_NAME=opac
            - OPAC_MONGODB_HOST=opac_mongo
            - OPAC_MONGODB_PORT=27017
            # - OPAC_MONGODB_HOST=cluster-mongo-opac.scielo.org
            # - OPAC_MONGODB_HOST=cluster-mongo-opac-qa.scielo.org
            # - OPAC_MONGODB_USER=opac.user
            # - OPAC_MONGODB_PASS=aes5ahZ8
            # - OPAC_MONGODB_USER=opac.user
            # - OPAC_MONGODB_PASS=aeQuu8pi
            - OPAC_DATABASE_DIR=/app/data
            - OPAC_MAIL_SERVER=mailhog
            - OPAC_MAIL_PORT=1025
            - OPAC_SECRET_KEY=s3kr3tk3y
        stdin_open: True
        tty: true
